### ISSUE TITLE
lesson 2 cell surface area

### ISSUE THREAD

**Issue by sofroniewn** [jni/i2k-skimage-napari#22]
Should this be "surface area" in um^2, or volume in um^3?

![image](https://user-images.githubusercontent.com/6531703/100561654-4d52de80-326e-11eb-953b-58f5861a1381.png)

**Comment by jni** [comment]
dang this would be a great one for skimage 0.18, because we have custom regionprops and there is a code example for how to estimate volume surface area with marching cubes here: https://github.com/scikit-image/scikit-image/issues/3797#issuecomment-471277056

so it would be an awesome challenge exercise. But we need skimage latest. There's a good chance I can release by tonight, but then it's *really* last minute stuff! 😬 (currently rc0 is out). I *could* specify scikit-image in pip with the rc in the requirements... Thoughts?

Anyway, the goal is volume here, but the regionprop is "area". It's pretty confusing (see https://github.com/scikit-image/scikit-image/issues/3812), but it's a simple constant multiplication of the existing "area" property.
